# Generated by Django 6.0.1 on 2026-01-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivos', '0002_alter_aduana_id_alter_aduana_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacion',
            name='id_aduana',
        ),
        migrations.RemoveField(
            model_name='importacion',
            name='oficializacion',
        ),
        migrations.AddField(
            model_name='importacion',
            name='aduana',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to='gestion_archivos.aduana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importacion',
            name='cliente',
            field=models.ForeignKey(default=20408389543, on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='gestion_archivos.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importacion',
            name='condicion_venta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='cantidad_unidades',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='fob_total_en_divisa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='fob_total_en_dolar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='numeracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='numero_destinacion',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importacion',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='pais_destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='puerto_embarque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='unitario_en_divisa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='aduana',
            table='aduanas',
        ),
    ]
