# Generated by Django 6.0.1 on 2026-01-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivos', '0003_remove_importacion_id_aduana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacion',
            name='id_aduana',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='nombre_transporte',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='oficializacion',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='puerto_embarque',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='vencimiento_embarque',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='vencimiento_preimposicion',
        ),
        migrations.RemoveField(
            model_name='exportacion',
            name='via',
        ),
        migrations.AddField(
            model_name='exportacion',
            name='aduana',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.PROTECT, related_name='exportaciones', to='gestion_archivos.aduana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportacion',
            name='cliente',
            field=models.ForeignKey(default=20408389543, on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='gestion_archivos.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportacion',
            name='comprador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='puerto_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='cantidad_unidades',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='condicion_venta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='fob_total_en_divisa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='fob_total_en_dolar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='numeracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='numero_destinacion',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='pais_destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='unitario_en_divisa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
