# Generated by Django 6.0.1 on 2026-01-15 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivos', '0004_remove_exportacion_id_aduana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportacion',
            old_name='pais_origen',
            new_name='codigo_afip',
        ),
        migrations.RenameField(
            model_name='exportacion',
            old_name='comprador',
            new_name='nombre_transporte',
        ),
        migrations.RenameField(
            model_name='exportacion',
            old_name='puerto_destino',
            new_name='puerto_embarque',
        ),
        migrations.AddField(
            model_name='exportacion',
            name='oficializacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='vencimiento_embarque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='vencimiento_preimposicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='aduana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_archivos.aduana'),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_archivos.cliente'),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='estado',
            field=models.CharField(default='Inicializada', max_length=50),
        ),
    ]
