services:
  backend:
    build: ./Backend
    container_name: sga_backend
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    environment:
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
    restart: always

  frontend:
      build: 
        context: ./Frontend
      container_name: sga_frontend
      ports:
        - "5173:5173"
      volumes:
        - ./Frontend:/app
        - /app/node_modules
      environment:
        - REACT_APP_API_URL=http://localhost:8000
      depends_on:
        - backend
      restart: always