# Generated by Django 6.0.1 on 2026-01-15 00:51

import apps.SGA.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'aduanas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cuit', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('domicilio', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio_actividad', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficializacion', models.DateField(blank=True, null=True)),
                ('numero_destinacion', models.CharField(blank=True, max_length=20, null=True)),
                ('via', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_transporte', models.CharField(blank=True, max_length=30, null=True)),
                ('vencimiento_preimposicion', models.DateField(blank=True, null=True)),
                ('vencimiento_embarque', models.DateField(blank=True, null=True)),
                ('condicion_venta', models.CharField(blank=True, max_length=15, null=True)),
                ('puerto_embarque', models.CharField(blank=True, max_length=30, null=True)),
                ('divisa', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_destino', models.CharField(blank=True, max_length=20, null=True)),
                ('unitario_en_divisa', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_unidades', models.FloatField(blank=True, null=True)),
                ('fob_total_en_divisa', models.FloatField(blank=True, null=True)),
                ('fob_total_en_dolar', models.FloatField(blank=True, null=True)),
                ('numeracion', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('baja', models.BooleanField(default=False)),
                ('id_aduana', models.ForeignKey(db_column='id_aduana', on_delete=django.db.models.deletion.CASCADE, to='SGA.aduana')),
            ],
            options={
                'db_table': 'exportaciones',
            },
        ),
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficializacion', models.DateField(blank=True, null=True)),
                ('numero_destinacion', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=30, null=True)),
                ('puerto_embarque', models.CharField(blank=True, max_length=30, null=True)),
                ('divisa', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_destino', models.CharField(blank=True, max_length=20, null=True)),
                ('unitario_en_divisa', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_unidades', models.FloatField(blank=True, null=True)),
                ('fob_total_en_divisa', models.FloatField(blank=True, null=True)),
                ('fob_total_en_dolar', models.FloatField(blank=True, null=True)),
                ('numeracion', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('baja', models.BooleanField(default=False)),
                ('id_aduana', models.ForeignKey(db_column='id_aduana', on_delete=django.db.models.deletion.CASCADE, to='SGA.aduana')),
            ],
            options={
                'db_table': 'importaciones',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=apps.SGA.models.generar_ruta_archivo)),
                ('tipo', models.IntegerField(choices=[(1, 'Cliente'), (2, 'Importación'), (3, 'Exportación')])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cuit_cliente', models.ForeignKey(blank=True, db_column='cuit_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGA.cliente')),
                ('id_exportacion', models.ForeignKey(blank=True, db_column='id_exportacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGA.exportacion')),
                ('id_importacion', models.ForeignKey(blank=True, db_column='id_importacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGA.importacion')),
            ],
            options={
                'db_table': 'archivos',
            },
        ),
    ]
