# Generated by Django 6.0.1 on 2026-01-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduana',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aduana',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='aduana',
            table=None,
        ),
    ]
