# Generated by Django 6.0.1 on 2026-02-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGA', '0005_rename_pais_origen_exportacion_codigo_afip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacion',
            name='oficializacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
