# Generated by Django 6.0.1 on 2026-02-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGA', '0006_importacion_oficializacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacion',
            name='via',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='importacion',
            name='via',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
