# Generated by Django 6.0.1 on 2026-02-18 20:36

from django.db import migrations

def crear_admin_desde_serializer(apps, schema_editor):
  
    User = apps.get_model('auth', 'User') 

    username = 'admin'
    email = 'admin@sga.com'
    password = '123456789'
    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(
            username=username,
            email=email,
            password=password,
            first_name='Administrador',
            last_name='SGA'
        )

def eliminar_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('SGA', '0007_exportacion_via_importacion_via'),
    ]

    operations = [
        migrations.RunPython(crear_admin_desde_serializer, eliminar_admin),
    ]